.PHONY: all deps fetch remove rebrand fix make

all: fetch remove rebrand fix make

deps: 
	nice -15 bash ./deps.sh

remove:
	nice -15 bash ./remove.sh

fetch:
	nice -15 bash ./fetch.sh

remove:
	nice -15 ./remove.js

rebrand:
	nice -15 bash ./rebrand.sh

fix:
	nice -15 ./fix.js

make:
	nice -15 bash ./make.sh